/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class top_ncserver_chatimg_Tools_dll_ClipboardImage */

#ifndef _Included_top_ncserver_chatimg_Tools_dll_ClipboardImage
#define _Included_top_ncserver_chatimg_Tools_dll_ClipboardImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_ncserver_chatimg_Tools_dll_ClipboardImage
 * Method:    getImageData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_top_ncserver_chatimg_Tools_dll_ClipboardImage_getImageData
  (JNIEnv *, jobject);

/*
 * Class:     top_ncserver_chatimg_Tools_dll_ClipboardImage
 * Method:    getImageWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_ncserver_chatimg_Tools_dll_ClipboardImage_getImageWidth
  (JNIEnv *, jobject);

/*
 * Class:     top_ncserver_chatimg_Tools_dll_ClipboardImage
 * Method:    getImageHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_ncserver_chatimg_Tools_dll_ClipboardImage_getImageHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
